In [1]:
import numpy as np
import os

In [2]:
os.listdir("dataset")

['ali', 'bhargav', 'chaitu', 'deepak', 'paramesh', 'srikanth']

In [3]:
class_map = {}

# Create dictionary to map integer labels to individuals
# Class_images will record number of images for each class
for index, directory in enumerate(os.listdir("dataset")):
    class_map[index] = directory[:]

In [4]:
class_map

{0: 'ali',
 1: 'bhargav',
 2: 'chaitu',
 3: 'deepak',
 4: 'paramesh',
 5: 'srikanth'}

In [5]:
d={}
for i in os.listdir('dataset'):
    d[i] = len(os.listdir('dataset'+'/'+i))
d

{'ali': 127,
 'bhargav': 147,
 'chaitu': 185,
 'deepak': 149,
 'paramesh': 194,
 'srikanth': 193}

In [6]:
import numpy as np
total = sum(d.values())
print(total)


995


In [7]:
c={}
for label, no_images in d.items():
    c[label] = (no_images /total ) * 100
c  

{'ali': 12.763819095477386,
 'bhargav': 14.773869346733667,
 'chaitu': 18.592964824120603,
 'deepak': 14.974874371859295,
 'paramesh': 19.497487437185928,
 'srikanth': 19.396984924623116}

In [8]:
from keras.preprocessing import image                  
from tqdm import tqdm
def path_to_tensor(img_path):
    # loads RGB image as PIL.Image.Image type
    img = image.load_img(img_path, target_size=(224, 224))
    # convert PIL.Image.Image type to 3D tensor with shape (224, 224, 3)
    x = image.img_to_array(img)
    # convert 3D tensor to 4D tensor with shape (1, 224, 224, 3) and return 4D tensor
    return np.expand_dims(x, axis=0)
def paths_to_tensor(img_paths):
    list_of_tensors = [path_to_tensor(img_path) for img_path in tqdm(img_paths)]
    return np.vstack(list_of_tensors)

Using TensorFlow backend.


In [9]:
names_map ={}
for index, directory in enumerate(os.listdir("dataset")):
    names_map[directory] = index
names_map

{'ali': 0,
 'bhargav': 1,
 'chaitu': 2,
 'deepak': 3,
 'paramesh': 4,
 'srikanth': 5}

In [10]:
from sklearn.datasets import load_files       
from keras.utils import np_utils
import numpy as np
from glob import glob
def load_dataset(path):
    data = load_files(path)
    files = np.array(data['filenames'])
    names = np.array([i.split('\\')[1] for i in data['filenames']])
    return files, names

In [11]:
files,targets = load_dataset('dataset')

In [12]:
files

array(['dataset\\chaitu\\User.5.58.jpg',
       'dataset\\srikanth\\User.2.90.jpg', 'dataset\\ali\\User.4.129.jpg',
       'dataset\\paramesh\\User.3.177.jpg',
       'dataset\\deepak\\User.7.5.jpg', 'dataset\\deepak\\User.7.119.jpg',
       'dataset\\deepak\\User.7.104.jpg',
       'dataset\\paramesh\\User.3.31.jpg',
       'dataset\\srikanth\\User.2.169.jpg',
       'dataset\\deepak\\User.7.93.jpg', 'dataset\\chaitu\\User.5.62.jpg',
       'dataset\\chaitu\\User.5.74.jpg', 'dataset\\ali\\User.4.8.jpg',
       'dataset\\ali\\User.4.94.jpg', 'dataset\\srikanth\\User.2.110.jpg',
       'dataset\\paramesh\\User.3.98.jpg',
       'dataset\\chaitu\\User.5.56.jpg', 'dataset\\chaitu\\User.5.41.jpg',
       'dataset\\bhargav\\User.1.82.jpg', 'dataset\\ali\\User.4.113.jpg',
       'dataset\\bhargav\\User.1.46.jpg', 'dataset\\ali\\User.4.125.jpg',
       'dataset\\paramesh\\User.3.19.jpg', 'dataset\\ali\\User.4.142.jpg',
       'dataset\\ali\\User.4.75.jpg', 'dataset\\srikanth\\User.2.114.jpg',

In [13]:
targets

array(['chaitu', 'srikanth', 'ali', 'paramesh', 'deepak', 'deepak',
       'deepak', 'paramesh', 'srikanth', 'deepak', 'chaitu', 'chaitu',
       'ali', 'ali', 'srikanth', 'paramesh', 'chaitu', 'chaitu',
       'bhargav', 'ali', 'bhargav', 'ali', 'paramesh', 'ali', 'ali',
       'srikanth', 'paramesh', 'srikanth', 'chaitu', 'deepak', 'paramesh',
       'paramesh', 'ali', 'bhargav', 'srikanth', 'chaitu', 'deepak',
       'chaitu', 'chaitu', 'deepak', 'chaitu', 'bhargav', 'chaitu',
       'srikanth', 'ali', 'paramesh', 'srikanth', 'paramesh', 'deepak',
       'srikanth', 'chaitu', 'chaitu', 'chaitu', 'paramesh', 'chaitu',
       'bhargav', 'srikanth', 'chaitu', 'srikanth', 'srikanth', 'deepak',
       'deepak', 'bhargav', 'bhargav', 'paramesh', 'srikanth', 'bhargav',
       'chaitu', 'chaitu', 'bhargav', 'deepak', 'chaitu', 'chaitu',
       'deepak', 'srikanth', 'paramesh', 'srikanth', 'deepak', 'paramesh',
       'paramesh', 'srikanth', 'paramesh', 'paramesh', 'bhargav',
       'deepak'

In [14]:
#categorical to one-hot encoding
targets = [names_map[i] for i in targets]
# print(targets)
targets = np_utils.to_categorical(targets, 7)

In [15]:
targets

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]], dtype=float32)

In [16]:
targets[52]

array([0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [17]:
import cv2
import matplotlib.pyplot as plt
img=cv2.imread(files[52])
plt.imshow(img)
plt.title(class_map[np.argmax(targets[52])])

Text(0.5, 1.0, 'chaitu')

In [18]:
# for normalization
tensors = paths_to_tensor(files).astype('float32')/255
tensors.shape

100%|███████████████████████████████████████████████████████████████████████████████| 995/995 [00:02<00:00, 481.39it/s]


(995, 224, 224, 3)

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(tensors, targets,random_state=42)

In [20]:
print(X_train.shape,  X_test.shape)
print(y_train.shape,  y_test.shape)

(746, 224, 224, 3) (249, 224, 224, 3)
(746, 7) (249, 7)


In [21]:
from keras.layers import Conv2D, MaxPooling2D, GlobalAveragePooling2D
from keras.layers import Dropout, Flatten, Dense
from keras.models import Sequential
model = Sequential()

model.add(Conv2D(16, (5,5), input_shape=(224, 224, 3), padding='same', activation='relu'))
model.add(Conv2D(32, (5,5), padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(16, (5,5), padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(7, activation='softmax'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 224, 224, 16)      1216      
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 224, 224, 32)      12832     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 112, 112, 32)      0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 112, 112, 16)      12816     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 56, 56, 16)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 50176)             0         
_________________________________________________________________
dense_1 (Dense)              (None, 64)               

In [22]:
model.compile(loss='binary_crossentropy',optimizer= "adam",metrics=['accuracy'])

In [23]:
from keras.callbacks import ModelCheckpoint  

### TODO: specify the number of epochs that you would like to use to train the model.

epochs = 5

### Do NOT modify the code below this line.

checkpointer = ModelCheckpoint(filepath='weights.best.from_scratch.hdf5', 
                               verbose=1, save_best_only=True)

history=model.fit(X_train, y_train,validation_split=0.2,
          epochs=epochs, batch_size=20, callbacks=[checkpointer], verbose=1)

Train on 596 samples, validate on 150 samples
Epoch 1/5
596/596 [==============================] - ETA: 5:43 - loss: 0.4206 - accuracy: 0.85 - ETA: 3:41 - loss: 0.6433 - accuracy: 0.82 - ETA: 2:58 - loss: 0.6344 - accuracy: 0.80 - ETA: 2:34 - loss: 0.5732 - accuracy: 0.81 - ETA: 2:18 - loss: 0.5386 - accuracy: 0.82 - ETA: 2:06 - loss: 0.5145 - accuracy: 0.83 - ETA: 1:57 - loss: 0.4965 - accuracy: 0.83 - ETA: 1:48 - loss: 0.4817 - accuracy: 0.83 - ETA: 1:41 - loss: 0.4694 - accuracy: 0.83 - ETA: 1:35 - loss: 0.4626 - accuracy: 0.84 - ETA: 1:29 - loss: 0.4600 - accuracy: 0.84 - ETA: 1:23 - loss: 0.4531 - accuracy: 0.84 - ETA: 1:17 - loss: 0.4476 - accuracy: 0.84 - ETA: 1:12 - loss: 0.4437 - accuracy: 0.84 - ETA: 1:07 - loss: 0.4410 - accuracy: 0.84 - ETA: 1:01 - loss: 0.4370 - accuracy: 0.84 - ETA: 57s - loss: 0.4336 - accuracy: 0.8471 - ETA: 52s - loss: 0.4296 - accuracy: 0.847 - ETA: 47s - loss: 0.4277 - accuracy: 0.848 - ETA: 42s - loss: 0.4236 - accuracy: 0.848 - ETA: 38s - loss: 0.4

In [24]:
model.evaluate(X_test,y_test)

249/249 [==============================] - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - 10s 42ms/step


[0.02313223839868384, 0.9965576529502869]

In [31]:
test_img = path_to_tensor('test/test2.jpg').astype('float32')/255


In [32]:
res = model.predict(X_test)
res

array([[8.53243649e-01, 4.02543601e-03, 8.93427432e-03, ...,
        3.51765938e-02, 3.04748653e-04, 1.58170669e-03],
       [9.43661273e-01, 6.45069449e-05, 4.14479815e-04, ...,
        8.22165515e-03, 4.57384303e-05, 1.82029507e-05],
       [1.38789746e-05, 9.98773754e-01, 2.08326837e-05, ...,
        5.85169590e-04, 4.77305090e-04, 8.41361398e-05],
       ...,
       [6.90703644e-07, 1.36491178e-06, 1.88616050e-05, ...,
        1.19605920e-05, 9.99963284e-01, 2.14558682e-09],
       [2.25666440e-06, 9.99870777e-01, 2.14501733e-06, ...,
        8.95116536e-05, 2.47459138e-05, 3.17181457e-06],
       [4.64246422e-03, 1.62954791e-04, 1.98054011e-03, ...,
        1.10737354e-04, 2.61501962e-04, 1.20008217e-05]], dtype=float32)

In [33]:
class_map[np.argmax(model.predict(test_img))]

'chaitu'

In [34]:
import cv2
import os

# Load the cascade
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

# To capture video from webcam. 
cap = cv2.VideoCapture(0)
# incase if we need to use a video file as input 
# cap = cv2.VideoCapture('filename.mp4')

Id=input('enter your id')
sampleNum=0

while True:
    # Read the frame
    _, img = cap.read()

    # Convert to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Detect the faces
    faces = face_cascade.detectMultiScale(gray, 1.1, 4)

    # Draw the rectangle around each face
    for (x, y, w, h) in faces:
        cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)
         #incrementing sample number 
        sampleNum=sampleNum+1
        #saving the captured face in the dataset folder
        cv2.imwrite("identify/User."+Id +'.'+ str(sampleNum) + ".jpg", gray[y:y+h,x:x+w])
        test =path_to_tensor("identify/User."+Id +'.'+ str(sampleNum) + ".jpg").astype('float32')/255
        
        
        # Draw a box around the face
       # cv2.rectangle(frame, (left, top), (right, bottom), (0, 0, 255), 2)

        # Draw a label with a name below the face
        #cv2.rectangle(img, (x, y- 25), (x+w, y+h), (0, 0, 255), cv2.FILLED)
        font = cv2.FONT_HERSHEY_DUPLEX
        cv2.putText(img, class_map[np.argmax(model.predict(test))], (x+ 6, y+h - 6), font, 0.5, (255, 0, 0), 2)
     
        
    # Display
    cv2.imshow('img', img)
    # Stop if escape key is pressed
    k = cv2.waitKey(500) & 0xff
    if k==27:
        break
     
    elif sampleNum>=200:
        break
        
# Release the VideoCapture object
cap.release()
cv2.destroyAllWindows()

enter your id2
